### ISSUE TITLE
使用packet sender软件进行tcp连接问题

### ISSUE THREAD

**Issue by shishi1yi** [jetlinks/jetlinks-community#96]
我通过步骤（添加协议——》产品——》设备——》网络组件——》设备网关）操作后，使用packet sender软件进行tcp连接，却得到Could not connect的结果，请问这是为什么？我通过telnet 连接我填写的IP和端口，是连的通的

![image](https://user-images.githubusercontent.com/50871933/131209351-ee30ab68-8022-4b6c-bdfe-96521918d752.png)

**Comment by zhou-hao** [comment]
docker运行的？设置端口绑定没

**Comment by shao1yi** [comment]
> docker运行的？设置端口绑定没
我是前后端都是本地idea运行的

**Comment by shao1yi** [comment]
我是idea本地运行的前后端




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jetlinks/jetlinks-community"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 上午9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jetlinks/jetlinks-community] 使用packet sender软件进行tcp连接问题 (#96)





 
docker运行的？设置端口绑定没
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
